mozilla/ecosystem-platform

docs/fxa-engineering/email.md
website/sidebars.json

I'd like to clean this up and make the language a little more formal so marking as WIP to get feedback from @mozilla/fxa-devs

add fxa-email documentation

---

website/core/Footer.js
website/pages/en/index.js

fixes #10
fixes mozilla/fxa#2898
Here's what a chart looks like that I added for testing to the l10n page I'm creating:
@clouserw, @johngruen  - r?

feat: Add support for Mermaid charts!

---

docs/fxa-engineering/fxa-localization.md
website/sidebars.json

fixes mozilla/fxa#2519
migrated from https://docs.google.com/document/d/1mFjt9beVZ9h-QGGKe-sXmsrBEGVIts4Nmf-FO9-4qVA/edit#

feat(docs): Add a doc on FxA localization

---

docs/fxa-engineering/fxa-systems.md
website/core/Footer.js
website/package-lock.json
website/sidebars.json
website/static/css/custom.css

@clouserw - r?
fixes mozilla/fxa#2633

feat(docs): Add service->service maps of the FxA universe

---

docs/fxa-engineering/fxa-content-server-ab-testing.md
website/sidebars.json

feat(docs): Add a document on experiments and A/B testing

---

docs/fxa-engineering/fxa-content-server-ab-testing.md

Goes along with https://github.com/mozilla/fxa/pull/3570

chore(docs): Update the experiment doc w/ info about `getAndReportExperimentGroup`

---

docs/fxa-engineering/fxa-logging.md
website/sidebars.json

doc: add logging

---

docs/process/integrating-with-fxa.md
docs/process/integration-with-subscription-platform.md

feat: add integration docs

---

docs/fxa-engineering/fxa-tests-circleci.md
website/sidebars.json

Just going to go ahead and open this as ready to review. There are some TBDs & bits left to add, but might be worth landing and going from there.

feat: add initial draft of FxA Circle CI docs

---

docs/fxa-engineering/functional-testing.md
website/sidebars.json

feat(docs): Add a deep dive on functional testing

---

docs/fxa-engineering/functional-testing.md

chore(docs): Sections on A/B testing and forcing UAs to func test doc

---

docs/fxa-engineering/release-process.md

Couple comments that would have been helpful for @6a68 and I.

chore(docs): Add more details to release process docs

---

docs/fxa-engineering/fxa-content-server-architecture.md

Fixes https://github.com/mozilla/fxa/issues/2839

fix(docs): Add more documentation about auth-broker implementations

---

docs/fxa-engineering/fxa-metrics.md

We use statsD style metrics in multiple FxA packages.  Let's mention it
in the docs.
Fixes https://github.com/mozilla/fxa/issues/3585
@mozilla/fxa-devs r?

chore(docs): mention statsd metrics

---

docs/fxa-engineering/fxa-sub-platform.md

chore(docs): document setting up auth/payments with some local secrets

---

docs/fxa-engineering/release-process.md

- made suggestions to increase the role of the release owner
closes #72

Add additional context for the role of Release Owner

---

docs/fxa-engineering/fxa-sub-platform.md

task(fxa-sub-plat): add docs for store download links

---

website/core/Footer.js

Because:
* We were using an old Mermaid.
This commit:
* Updates the mermaid JS.

chore: update mermaid

---

docs/fxa-engineering/functional-testing.md

```
- Added updates about the smoke tests and regression test suites.
- Removed any/all information about TeamCity
- Added info about Slack notification in event of Smoke test failures.
```
@mozilla/fxa-devs Please review! Thanks!

docs(functional_tests): modify and add latest updates for functional tests

---

docs/fxa-engineering/fxa-automation-testplan.md

`created an automation test plan for FxA tests`

docs(automation_test_plan): create an automation test plan

---

website/sidebars.json

adding menu to the `sidebar.json `file

docs(automation_testplan): add sidebar files

---

docs/fxa-engineering/fxa-sub-platform.md

How set config for PayPal and some high level overview/how to.

chore(docs): update docs for SubPlat+PayPal

---

docs/fxa-engineering/release-process.md

Document how to temp deploy to stage

---

docs/reference/metrics.md
docs/relying-parties/metrics-for-relying-parties.md

Closes https://github.com/mozilla/fxa/issues/9087

Add metrics opt-out for relying parties

---

docs/platform/sub-plat/coupons.md

Coupon Documentation

---

docs/reference/team-processes/development-process.md
docs/reference/team-processes/triage-process.md

Open for feedback, I'm fine modifying anything 👍
closes https://github.com/mozilla/fxa/issues/12166

Update dependencies section of triage + add PR section of development

---

docs/reference/team-processes/development-process.md
docs/reference/team-processes/release-process.md

As usual, anyone please feel free to leave any comments for tweaks or additions. 🙂
Closes mozilla/fxa/issues/12105

chore(docs): Update Release Owner docs

---

docs/relying-parties/tutorials/integration-with-subscription-platform.md

Add information of how to subscribe to a staging subscription for RP

chore(subplat) add information on subscribing on staging

---

docs/how-tos/using-sentry-locally.md

- Use code block for env settings.
- Add tip about how to locate dsn settings.

Update formatting on setry env settings

---

docs/tutorials/subscription-platform.md

chore(auth): add dev docs for making test IAP subscriptions

---

docs/reference/style-guides/react-style-guide.md

closes mozilla/fxa/issues/13596
closes mozilla/fxa/issues/13597

Add a 'Custom Hooks' and 'Context' section to the React style guide

---

docs/tutorials/subscription-platform.md

chore(docs): update Stripe metadata descriptions for IAP identifiers

---

docs/relying-parties/how-twos/apple-iap.md
docs/relying-parties/tutorials/integration-with-subscription-platform.md
sidebars.js

Closes: #[FXA-6443](https://mozilla-hub.atlassian.net/browse/FXA-6443)

chore(docs): add Apple IAP RP integration docs

---

docs/explanation/metrics.md

- we need to clarify how the events are validated before they are logged
- includes how events are validated
Closes: [FXA-6944](https://mozilla-hub.atlassian.net/browse/FXA-6944)

chore(docs): Add event validation stages

---

docs/relying-parties/reference/metrics-for-relying-parties.md

- we do not have any documentation regarding Subscriptions Services data source
- adds a section that lists and description the sources from which we obtain subscriptions data.
Closes: [FXA-6943](https://mozilla-hub.atlassian.net/browse/FXA-6943)

chore(docs): Add section regarding Subscriptions Services data sources

---

docs/reference/database-structure.md

This flags all the confidential fields (thx @vbudhram )

update db docs

---

docs/reference/npm-scripts-and-nx.md
sidebars.js

Some more guidelines for how to structure npm scripts to ensure consistency and compatibility with nx.

Add doc about npm script names and nx

---

docs/relying-parties/tutorials/integrating-with-fxa.md

Because:
* We want to ensure RPs acting as a resource server have supporting documentation.
This commit:
* Adds appropriate clarifications to the docs for RPs acting as a resource server.
Closes FXA-7474

chore: add docs for resource servers

---

docs/reference/npm-scripts-and-nx.md
docs/tutorials/subscription-platform.md

chore(docs): Update how-to docs for Nx and Contentful

---

docs/tutorials/subscription-platform.md

* We want to ensure our documentation is up-to-date.
* Updates the docs to include the required Contentful environment variables.
Closes FXA-8211

chore(docs): update docs to include the required Contentful environment

---

docs/reference/npm-scripts-and-nx.md

- we want to note additional changes included when creating a Nx library
- notes the changes

chore(docs): Update guide for creating Nx library

---

docs/how-tos/rotating-secrets.md
sidebars.js

Relates to: [FXA-8371](https://mozilla-hub.atlassian.net/browse/FXA-8371)

chore(docs): add how-to for rotating secrets

---

docs/reference/npm-scripts-and-nx.md

This change is dependent on [fxa/pull/15925](https://github.com/mozilla/fxa/pull/15925), and should be merged once that PR is approved and merged.

feat(nx): remove "rootDir" step for nx library

---

docs/reference/functional-testing.md

Update the 'functional test' reference page with Playwright information.

update playwright functional test docs

---

docs/reference/automation-testplan.md

Update Playwright info in the automation test plan and remove the outdated info.

update Playwright info in the automation testplan

---

docs/relying-parties/reference/sub-plat-contentful.md

- Updates docs to include how we are able to search and filter down relevant content by using metadata as well

fix(docs): Revise Contentful doc - search

---

docs/reference/functional-testing.md

Update steps for Debugging the tests when there is a CircleCI failure

Update test debugging steps

---

docs/reference/team-processes/release-process.md

Added link for debugging test steps to RO duties.

add debug test failure steps to RO duties

---

docs/reference/functional-testing.md

Added guidelines and best practices for writing functional tests that were discussed during work week.

add guidelines and best practices for functional tests

---

docs/reference/functional-testing.md

Closes: # FXA-9740
Relates to: https://github.com/mozilla/fxa/pull/17030

docs(functional-tests): add skip and fixme clarification and update best practices and guidelines

---

docs/reference/canceling-subscriptions-to-plan.md
sidebars.js

- Adds a guide to help sunset plans

chore(docs): Add guide to sunset plans

---

docs/relying-parties/reference/sub-plat-coupons.md

- Updates the coupon page informing that the coupon name will also appear on the customer's Subscription Management page

chore(docs): Update SubPlat Coupon page

---

docs/reference/mobile-specifics.md

This list should match what we have in `fxa/_scripts/ports.txt`.

Update adb reverse ports

---

docs/how-tos/local-emails-with-maildev.md
docs/reference/team-processes/development-process.md
docs/reference/team-processes/triage-process.md

Updates triage links to current location/hrefs.
(Fixing one typo along the way.)

fix(docs): Bugzilla triage links

---

docs/reference/team-processes/triage-process.md

- Updates the guide for SubPlat triage responsibilities

Update guide for SubPlat Triage responsibilities

---

docs/reference/team-processes/triage-process.md

- updates outdated information within triage guide

chore(docs): Update Triage guide

---

docs/relying-parties/reference/sub-plat-strapi.md

chore(docs): Update Strapi onboarding guide

---

docs/relying-parties/reference/sub-plat-strapi.md

- updates the Getting Started section to include the links to each Strapi instance for our RPs

chore(docs): Update Strapi - Getting Started

---

docs/reference/mobile-specifics.md

FxA PR to remove config-fxios: https://github.com/mozilla/fxa/pull/18135

Revise Firefox for iOS documentation

---

docs/explanation/onepw-protocol.md

Because I want to link to a specific section of the page that I cannot at the moment

chore(docs): update onepw doc headers so they have id attrs

---

docs/explanation/pairing-flow-architecture.md

Changing the rect rgb fill from a dark purple (rgb(100, 55, 100)) to a lighter purple (rgb(219, 190, 219)) in order to make the black text on it readable.

Update pairing-flow-architecture.md mermaid diagram
