mozilla/ecosystem-platform

docs/engineering/dev-process.md
Without line breaks in the parent list, child lists were being rendered all as paragraphs. Also tweaked the `0.`'s to `1.`'s because GitHub's list styling doesn't seem to like 0-index lists
=> Add line breaks to fix rendering of lists in fxa dev-process

docs/features/firefox-sync/bookmarks-feature.md, docs/features/firefox-sync/history-feature.md, docs/features/firefox-sync/password-management-feature.md, docs/features/firefox-sync/sync-feature.md, website/sidebars.json
This is a starting point for the Logins component information that should exist as a part of the larger body of work related to logins sync and storage (aka password management).
I've also modified the sidebar structure to refocus on a hierarchy based on features vs teams.
=> initial draft for logins component docs

docs/fxa-engineering/fxa-jwt-access-tokens.md, website/sidebars.json
fixes mozilla/fxa#2796
Taken from https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/fxa-oauth-server/docs/jwt-access-tokens.md, so we should probably delete that so there is only one source of truth.
=> feat(docs): Add docs about JWT access tokens

docs/fxa-engineering/fxa-dev-process.md
Updating labels to be in line with QA's standards.  I'm not sure how useful having these labels in the docs are to be honest, since we could just link to the github page, but... at least they won't be wrong for now.
=> update labels to be in line w/ QA standards

docs/fxa-engineering/fxa-oauth-webchannel-protocol.md, docs/fxa-engineering/fxa-webchannel-protocol.md, website/sidebars.json
* One for the desktop, one for OAuth.
* Taken from the fxa/packages/fxa-content-server repo & updated for clarity
=> feat(docs): Add docs on the WebChannel protocols

docs/fxa-engineering/fxa-metrics.md
Performance metrics in Payments is in a state of flux.  Let's leave it
out of the metrics doc until we have something that's actually working.
=> chore(docs): remove references to Payments perf metrics

docs/relying-parties/metrics-for-relying-parties.md
Borrowing liberally from Leif's data review doc (https://docs.google.com/document/d/1rMfO6BAlXycX0U9-R4P3Z63kzjlh2jNEL_0QKDYjlv8/edit), this gives us a starting point for docs.
=>  feat(docs): add docs for the RP 'engage' ping 

website/static/css/custom.css
This change correctly specifies the name of the web font used for text ("Inter UI", not "inter"), and also specifies the same header and content fallback font-families used in the production Firefox Accounts website.
Because: I got tired of squinting at a tiny serif font while reading metrics and release docs :-)
=> fix(style): Correct body font and use FxA font-family for fallbacks

PR_TEMPLATE.md, docs/about/the-teams.md, docs/features/firefox-sync/storage-feature.md, docs/process/sync-testing.md, docs/process/using-the-staging-environment.md, website/pages/en/index.js, website/sidebars.json
We have [a goal this quarter](https://docs.google.com/spreadsheets/d/1RjDzgs-CMuqRD5K18SbkD__RwgBiDcgmLiCqjwTbjOU/edit#gid=21744728) to make Sync more easily testable against staging.
This is step one; start moving some of our existing docs over here. I plan to continue this work throughout the quarter. This effort specifically involves getting the contents of [this doc](https://docs.google.com/document/d/1KnFdE1ee-yv8En5QaPoRj3x2s9kTESoW0lGNh2LwIrI/edit#heading=h.m5439epyhnxm) moved over.
For reference, the meta issue tracking this work lives [here](https://github.com/mozilla-services/services-engineering/issues/29).
Read along :) Anything that should be moved or changed?
Closes [mozilla-services/services-engineering #25](https://github.com/mozilla-services/services-engineering/issues/25) …
=> feat: consolidate sync testing docs

docs/fxa-engineering/release-process.md
Add the icon release info from [#3416](https://github.com/mozilla/fxa/issues/3416#issuecomment-562281131) to the release docs.
=> Document icon release info

docs/fxa-engineering/vscode-development.md, website/sidebars.json
Because:
* Most of the team uses VS Code and we have additional helpers that can
be used.
This commit:
* Add's documentation on how to use the repo in VS Code with other
helpful tips and recommendations.
Closes mozilla/fxa#2693
=> feat: add vs code docs

docs/fxa-engineering/fxa-sub-platform.md, website/sidebars.json
Because:
* We didn't document with the project how to run the subscription
platform related pieces.
This commit:
* Add's docs on what configuration/keys are needed.
Closes mozilla/fxa#4178
Co-authored-by: Lauren Zugai <lauren@zugai.com>
=> feat: add subscription platform docs

docs/fxa-engineering/vscode-development.md
Because:
* It can be difficult to explain how to use the tasks in VS Code.
This commit:
* Embeds two short videos showing usage of the debugger.
=> feat: add demo videos of using vs code

docs/fxa-engineering/fxa-sub-platform.md
Include description of new Stripe metadata conventions added for a
couple of issues recently closed on FxA
* https://github.com/mozilla/fxa/issues/4741
* https://github.com/mozilla/fxa/issues/5121
=> Update docs for product and subscription metadata in Stripe

website/siteConfig.js
👋 team,
I am working on DocSearch. [We have an integration for Docusaurus](https://docusaurus.io/docs/en/search#enabling-the-search-bar). We thought it is a shame you can not also used this search that you can [find on reactjs for example](https://reactjs.org/).
This PR will add DocSearch to the documentation website. It will allow an user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.
Let me know if you need anything.
resolves #26
=> feat: add DocSearch as recommended by docusaurus

docs/fxa-engineering/release-process.md
Ran into an issue earlier today where `git fetch origin` didn't pull in several tags. I ran the release script and noticed in the diff that it didn't contain changelog updates from 1.174.2, but running `git fetch origin --tags` specifically pulled in the missing tags.
=> chore(docs): Add a tip around pulling in new code/tags to release process doc

docs/fxa-engineering/fxa-sub-platform.md
- add documentation for how we will be storing terms of service and privacy notice links in Stripe metadata
closes https://github.com/mozilla/fxa/issues/5583
=> feat (subscription docs) - add documentation for tos and pn metadata

docs/features/firefox-accounts/ecosystem-telemetry.md, website/sidebars.json
We'll populate this page with public-facing documentation once all the pieces are in place,
but in the meantime it will be useful to have a live URL that we can link to from e.g.
in-code telemetry docs.
**Update**: I went ahead and added some actual content to this page, although it could probably still be fleshed out a little more (and have some diagrams added for clarity).
=> Add a docs page for Account Ecosystem Telemetry.

docs/features/firefox-accounts/ecosystem-telemetry.md
Sorry, I landed https://github.com/mozilla/ecosystem-platform/pull/93 too early and have reverted it on master. These are the same docs as in that PR, but as a *draft* PR so that I can't accidentally land them before other related docs go live 😬 
(These docs are not secret, they're just part of a broader coordinated rollout strategy)
=> task(ecosystem-telemetry): Flesh out the docs for Account Ecosystem Telemetry

docs/process/using-the-staging-environment.md
I noticed recently that the [setting to use the iOS staging server](https://github.com/mozilla-mobile/firefox-ios/issues/7101) changed. Updating docs here to reflect that.
Instructions make sense? Here's what they look like locally:
Closes [#97](https://github.com/mozilla/ecosystem-platform/issues/97).
=> Updating instructions for testing sync in iOS against staging

docs/process/using-the-staging-environment.md, website/package-lock.json, website/package.json
Now that Fenix is live, I want to make sure we have docs to share about how to test it against staging sync servers. I also added a few tidbits to package.json, and upgraded docusaurus (which fixed a bunch of npm warnings).
Read it - make sense?
Closes https://github.com/mozilla/ecosystem-platform/issues/94.
=> Add details for how to test Fenix against staging, and minor package.json tweaks

docs/fxa-engineering/fxa-work-breakdown-process.md, website/sidebars.json
I've had these docs open in tabs since, like, the before-times.  Finally turning them into a PR.
=> add work breakdown docs

docs/fxa-engineering/fxa-sub-platform.md
Because:
* It can be difficult to understand the interactions involved in the
PayPal checkout flow with reference transactions.
This commit:
* Adds a ladder diagram describing the steps identified in completing a
purchase successfully with PayPal.
Issue mozilla/fxa#7033
=> feat: add paypal checkout flow

docs/fxa-engineering/fxa-sub-platform.md
Doc for subscription support form field added in FXA-2434 (https://github.com/mozilla/fxa/issues/6220).
=> docs(subscriptions): add doc for 'support:app:' Stripe product metadata

docs/fxa-engineering/fxa-github.md, website/sidebars.json
In the future we can put some docs for our repository strategies too, if we get them, but short term I think this will help organize our permissions at least.
=> Add documentation for our GitHub permissions

docs/fxa-engineering/fxa-jwt-access-tokens.md
Inherited from BrowserID, some internal Mozilla reliers need access
to special `fxa-*` prefixed claims. These were only documented in
the fxa-auth-server API docs about BrowserID, so I've copied the
text over to the OAuth docs to make it easier to find, and added
a few notes on how we expect the values to be used.
=> Document some internal `fxa-*` claims inside JWT access tokens.

docs/reference/system-diagrams.md
I just noticed some references to subhub here which are all out of date.  I thought we'd need to sub in the payments-server for a bunch, but it seems to already exist in the diagrams, so, I just removed subhub.  There will be more changes to make here in the near future, (eg. when @dannycoates drops mysql-db-auth-server) but this is a step in the right direction.
=> remove subhub

docs/team-process/development-process.md, docs/team-process/release-process.md, docs/team-process/triage-process.md, docs/team-process/work-breakdown-process.md, sidebars.js
This is _mostly_ a port of the [Triage Owner Duties doc](https://docs.google.com/document/d/1wfbNGg4OPL4UeZ6YPIiiuNSYDOSW21W_kF07vpRBIyg/edit#) with some additions and clarifications based on feedback the last couple of months. I'll add a note at the top of the doc with a link here noting its deprecation. 
I'm recommending taking on about 50% of a normal sprint workload when being the triage owner. We've experimented with this number and commiting to no work seemed a little lax, and I don't believe committing to around 70% as previously discussed gives enough leeway for all the responsibilities outlined here, especially dependabot, which I think we can manage better as a team. I think it could be argued that SubPlat triage owner can take on _slightly_ more work since they don't need to …
=> Add Team Processes section, create Triage Process, modify Dev/Release Process

docs/tutorials/subscription-platform.md
Because:
* Added a new parameter to the product stripe metadata for the
cancellation survey URL.
This commit:
* Adds the documentation detailing  the new parameter.
Closes #
=> feat(subscription): stripe meta cancel survey url

docs/explanation/metrics.md, docs/how-tos/working-with-metrics.md, docs/reference/metrics.md, sidebars.js
This changes our metrics docs from being a monolithic "metrics.md" and tries to embrace the [divio system](https://documentation.divio.com/introduction/) the docs are modeled after.  I wrote the reference one from scratch so it has some stuff which might be new to some folks.  The other two pages are mostly from the old docs, but I updated them to remove amplitude and redshift references and brought our history doc up to date.
=> Reorganize metrics docs

docs/how-tos/using-sentry-locally.md, sidebars.js
A brief overview of how to configure FxA so that sentry is enabled when running the stack locally.
=> Provides instructions for using sentry during local development

docusaurus.config.js, package.json, sidebars.js, yarn.lock
Alright, this pulls in the swagger API docs.  Some caveats:
1) It pulls in on build, so, it wouldn't update unless you rebuild here.  Probably easily solved with a cron job in github actions?
2) Solved ~~The sidebar ordering is based on the order in swagger.json which is kinda scattered right now.  Redoc [claims to support](https://github.com/Redocly/redoc#redoc-options-object) things like `sortOperationsAlphabetically` but I didn't get it working.~~ 
3) Solved ~~Some of the endpoints aren't showing up in the nav bar.  These are `operations` in swagger-speak and if we have a summary (which we often have as "🔒 sessionToken") it won't show the operations.  There is [a bug on file](https://github.com/Redocly/redoc/issues/753) but I think I agree with the reasoning behind it being open for …
=> Add redocusaurus support. Fix FXA-4901

docs/reference/using-swagger-for-api-documentation.md, sidebars.js
Because:
* it help others add and update our current API documentation
This commit:
* outlines how to modify our documentation
Closes [#12621](https://github.com/mozilla/fxa/issues/12621)
=> docs(swagger): Add guide to modify Swagger API documentation

docs/reference/using-swagger-for-api-documentation.md, docusaurus.config.js, sidebars.js
- the Swagger JSON file generates the OAuth Server API documentation into a separate section within its doc with the Auth Server API documentation. Therefore, we should revise the path from `/api/auth-server` since not just the Auth Server API documentation can be found through the URL (see screenshot below)
- updates the path to `/api`
=> docs(Swagger): Revise API doc URL from /api/auth-server to /api

docs/reference/emails.md, docs/reference/storybook-deploys-with-circleci.md, docs/reference/tests-in-circleci.md, docs/relying-parties/reference/sub-plat-overview.md
Because:
* There's a static link available to the latest Storybook builds on main
This commit:
* Updates a few links.
* Remove section of deleted script.
* Adds a new section to Sub Plat overview mentioning Storybook.
Closes #
=> feat: add static storybook links

docs/how-tos/using-sentry-locally.md, docs/reference/storybook-deploys-with-circleci.md, docs/reference/team-processes/release-process.md
-Couple more details on the RO page based on a couple of questions a new RO recently had
-Minor Sentry page tweaks based on a question recently asked around root-level `.env`
-Storybook CI page tweaks, the image was huge and we needed links to the packages, and placed the "latest" link in an admonition
=> Small tweaks on local Sentry, storybook CI, release process

docs/reference/style-guides/general-best-practices.md, docs/reference/style-guides/node-style-guide.md, docs/reference/style-guides/react-style-guide.md, sidebars.js
Because:
* The FxA and SubPlat need a shared style guide to ensure uniformity
across the different react front-ends owned by both teams.
This commit:
* Adds a first version of the style guide, based heavily on the Airbnb
react style guide.
=> chore(style-guide): react style guide

docs/how-tos/using-sentry-locally.md
Because:
- Different users have had different experiences getting dotenv-cli to install.
This Commit:
- Removes install command because apparently it's flawed.
- Simply instruct users to install dotenv globally. This side steps any questions about yarn vs npm vs npx vs yarn dlx and leaves it up to the user.
=> Remove explicit install instructions for dotenv-cli.

package.json, yarn.lock
Reverts mozilla/ecosystem-platform#234
Spotted by Dan, this is likely breaking the deploy.
=> Revert "chore(deps): bump @mdx-js/react from 1.6.22 to 2.1.2"

docs/tutorials/development-setup.mdx
This fixes the links for secrets setup listed in the development setup guide.
Both links now point at their respective READMEs
=> fix: Development setup secrets links

docs/tutorials/subscription-platform.md
Also removes the default product config section as that config should be removed entirely; see [FXA-3846](https://mozilla-hub.atlassian.net/browse/FXA-3846).
Closes: #FXA-5819
=> Clarify IAP config is plan-level only

docs/tutorials/subscription-platform.md
Because:
* we want accurate docs that reflect necessary product config
This commit:
* marks productSet as required
Closes #FXA-5963
=> chore(docs): mark ProducSet as Required Metadata Field

docs/reference/style-guides/node-style-guide.md
Because:
* We want to have a style guide for our backend code that ensures consistency, maintainability, and readability.
This commit:
* Adds a backend style guide that covers legacy code, and the new NestJS code and component structure.
Closes FXA-6050
=> docs: add backend style guide

architecture-diagrams/README.md, docs/reference/system-diagrams.md
Because:
* The README wasn't rendering the lettered list correctly.
* The system diagrams docs was missing a link to the architecture diagrams README.
This commit:
* Fixes the bullet point list in the architecture diagrams README.
* Adds a link to the architecture diagrams README from the system diagrams docs.
=> chore(docs): fix README bullet point and link from diagrams

docs/tutorials/subscription-platform.md
Because:
* Certain metadata fields need to be prepended by `product:`.
This commit:
* Updates `successActionButtonLabel` fields with `product:`.
Closes #
=> docs(payments): prepend product: where required

docs/reference/team-processes/pull-request-review-guidelines.md, sidebars.js
Because:
* The Subscription Platform team discussed pull request review guidelines during their work week in December 2022.
This commit:
* Adds the pr review guidelines to ecosystem docs.
Closes #FXA-6763
=> docs: add pull request review guidelines

docs/how-tos/ci-guidelines.md
Because:
- We removed colon characters from script names that weren't intended to be global
This Commit:
- Updates references to these npm scripts
=> Update npm script names

docs/how-tos/local-emails-with-maildev.md
Because:
* yarn global is deprecated
This commit:
* Replace with npm in maildev how-to doc
Closes #
=> fix(docs): Update maildev install command

docs/relying-parties/how-tos/google-iap.md, docs/relying-parties/tutorials/integration-with-subscription-platform.md, sidebars.js
Because:
- We want to ensure our documentation, in particular for IAP integration, is up to date
This commit:
- Adds Google IAP RP integration to our ecosystem docs
Closes FXA-6746
=> chore(docs): add Google IAP RP integration docs

docs/reference/tokens.md
In the OAuth Access Tokens section and the OIDC Identity Tokens section, there were two typos in the markdown link formatting. This fixes those.
=> Update tokens.md to fix HTML link formatting

docs/tutorials/subscription-platform.md
Because:
* Support for new fields in Stripe metadata for newsletter changes.
This commit:
* Adds documentation for newsletterSlug and newsletterLabelTextCode.
Closes #FXA-7611
=> feat(payments): config newsletter slug and copy

docs/tutorials/subscription-platform.md
- adds a note regarding `.env` file preference with Nx
=> chore(docs): Update PayPal integration page

docs/reference/team-processes/development-process.md
Because:
* We want to document the process for polish/quick-fix PR's.
This commit:
* Adds a section to the development process doc on polish/quick-fix PR's and how they should be handled.
Closees #FXA-8134
=> feat: Add section on polish/quick-fix PR's

docs/reference/style-guides/node-style-guide.md
Because:
* We want to document the architecture patterns we use in our node services and applications.
This commit:
* Adds a new section to the node style guide that documents the architecture patterns we use in our node services and applications.
Close #FXA-8135
=> feat: extend structure node guide with architecture patterns

docs/reference/team-processes/release-process.md
Update the release process doc to add steps for Release owner's responsibility when there is a test failure during release.
This closes [FXA-8200](https://mozilla-hub.atlassian.net/browse/FXA-8200)
=> update release process doc

docs/relying-parties/reference/sub-plat-contentful.md
- Updates the Contentful Onboarding docs based on feedback and new knowledge:
=> docs(contentful): Update Contentful Onboarding doc

docs/explanation/content-server-architecture.md, docs/reference/emails.md, docs/reference/localization.md
Because:
* Localization documentation was out of date
This commit:
* Update localization docs with current process, including Fluent and updates to extraction and build processes
Closes #FXA-4985
=> feat(l10n): Update l10n docs

docs/reference/team-processes/triage-process.md
- Includes the following updates to the Triage Ownership documentation:
- [FXA-6450](https://mozilla-hub.atlassian.net/FXA-6450) and [FXA-4271](https://mozilla-hub.atlassian.net/FXA-4271)
SubPlat TO priorization
Stripe Triage
Grafana
=> chore(docs): Revise TO documentation

docs/reference/npm-scripts-and-nx.md
Because:
* Command to generate nx library's needed updates
This commit:
* Updated generate nx library command with importPath and test-unit and test-integration instructions.
Closes #
=> chore(docs): update nx library generator command

docs/tutorials/development-setup.mdx
I'm not sure if `jq` is installed on ubuntu by default or not, but I was following the ubuntu instruction to install the necessary packages on my Manjaro machine, and I faced some issues during the local setup since I didn't have `jq` installed. I assume other people could benefit from this change as well.
=> Update development-setup.mdx to add jq as dependencies

docs/reference/style-guides/node-style-guide.md
Because:
* Missing a section for config and some examples
This commit:
* Added a section for config
* Added a section for types
* Updated example and added more context for factories
Closes #
=> chore(docs): node style guide updates

docs/reference/npm-scripts-and-nx.md
Because:
- Nx library creation instructions need to be updated to match the new build and testing targets.
- Library creation instructions were difficult to parse
This commit:
- Updates the library creation script
- Simplifies and clarifies the creation instructions
- Related code change can be found here, [mozilla/fxa#17133](https://github.com/mozilla/fxa/pull/17133)
Closes #FXA-9879
=> chore(docs): simplify nx library creation

docs/relying-parties/reference/sub-plat-coupons.md
- links Coupons API docs to the Subscription Coupons section
=> chore(docs): Link Coupon API doc to Coupon section

docs/reference/team-processes/triage-process.md
Happy to make any changes here.
closes FXA-10924 (not sure our Jira link works over here?)
=> chore(docs): Update FxA triage ownership page w/daily update template

docs/tutorials/development-setup.mdx
During FxA Development Setup, there have been multiple encounters with a missing auth-server key.  The solution is simple, and including it in the docs can save time and frustration.
This PR adds a few troubleshooting steps, including specific instruction on how to generate missing openID key if needed. 
Closes FXA-11444
=> docs: update development setup troubleshooting

docs/tutorials/development-setup.mdx
We encountered an issue where the FxA stack has trouble starting after running `yarn start` – the NX process hangs.  This PR documents the issue and adds a potential solution, skipping NX cache.
=> docs: update development setup cache troubleshooting

docs/reference/npm-scripts-and-nx.md
Relates back to FXA-11333. All of the configs needed to be updated to get JUnit output, so this makes sure new projects also follow the pattern
=> docs: include junit output for jest.config.ts example for NX packages

docs/how-tos/working-with-metrics.md
Because:
* we need to rebuild fxa-shared after generating a new glean metric for settings, otherwise unit tests (and possibly other stuff) can error
This commit:
* updates the instruction to include `yarn build`
=> doc(metrics): update how-to guide for creating new frontend metrics
